### ISSUE TITLE
RFNF: Add a 'write' example to NetCoreConsoleClient

### ISSUE THREAD

**Issue by dawonn** [OPCFoundation/UA-.NETStandard-Samples#15]
I found the NetCoreConsoleClient example to be the easiest to learn from, but it would have been really really great if there was an example of how to write to a variable in that example as well.

**Comment by mregen** [comment]
there is now a sample how to write in the `UAClient`. https://github.com/OPCFoundation/UA-.NETStandard/blob/master/Applications/ConsoleReferenceClient/UAClient.cs

**Comment by SanderNID** [comment]
I implemented the code from [kevinjhang] from Oct 15, 2018.
This works perfect as long as the value is a boolean or integer etc.

I am trying to read and write a struct.
**Reading is possible:**
I created the following object:
![image](https://github.com/OPCFoundation/UA-.NETStandard-Samples/assets/74061419/24eef0f4-61c0-4a74-b368-e2f08473cf65)

I decode the result:
![image](https://github.com/OPCFoundation/UA-.NETStandard-Samples/assets/74061419/ea819828-fd87-4d6e-a81f-982d1b03205e)

The input value is at this moment an array of bytes: byte[] {0, 1, 0}
![image](https://github.com/OPCFoundation/UA-.NETStandard-Samples/assets/74061419/e2f8d7bd-bee8-48f9-b821-417ff3809717)

Now I want to write the same byte[] {1,0,1}, but I constantly get the following [BadTypeMismatch] error.
How can I write a byte[] to a struct instead of writing every value seperately?

Below my code to write:
![image](https://github.com/OPCFoundation/UA-.NETStandard-Samples/assets/74061419/ec839a25-5443-4109-ab61-9e7bbd4bfd05)
